import streamlit as st

st.header("Our Team🤝")
st.divider()
a,space,b=st.columns((1,0.6,1))
ele=st.container()
a.image("ad.png")
b.subheader("Adya Omnkar Panda ")
b.write("AI|ML and Data Science Enthusiast")
b.markdown("[LinkedIn👝](https://www.linkedin.com/in/adya-omnkar-panda-0b1b3b1b3/)")
st.markdown("")
a.image("rt.png")
b.divider()
b.divider()
b.subheader("Rituparna Satpathy ")
b.write("Android Developer")
b.markdown("[LinkedIn👝](https://www.linkedin.com/in/rituparna-satpathy-1b9636311?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app)")
st.markdown("")
a.image("ur.png")
b.divider()
b.divider()
b.subheader("Urbi Purohit")
b.write("Machine Learning")
b.markdown("[LinkedIn👝](https://www.linkedin.com/in/urbi-purohit-5541b7300/)")
st.markdown("")
a.image("ar.png")
b.divider()
b.divider()
b.subheader("Aryan Rath")
b.write("Web Developer")
b.markdown("[LinkedIn👝](https://www.linkedin.com/in/urbi-purohit-5541b7300/)")